### ISSUE TITLE
請在 Google 雲端硬碟以外的地方提供編譯好的字型

### ISSUE THREAD

**Issue by s8321414** [l10n-tw/cwtex-q-fonts#1]
如標題所說，因為 Google 雲端硬碟對使用 CLI 工具下載的使用者非常的不友善，請提供一個在更新時，只需更改版本號即可更新的位址。

**Comment by chenpanliao** [comment]
謝謝你的意見。我以 L10n Taiwan 的名義開了一個 cwtex-q-fonts-TTFs 專門放 TTF，請見
https://github.com/l10n-tw/cwtex-q-fonts-TTFs/releases

**Comment by s8321414** [comment]
太好了~感謝您~

**Comment by zerng07** [comment]
對了， https://github.com/l10n-tw/cwtex-q-fonts/releases 不算嗎？好奇。

**Comment by zerng07** [comment]
我發現裡面沒有 ttf。瞭解了。

**Comment by s8321414** [comment]
呃......
