### ISSUE TITLE
"真" is displayed as the variant. should be displayed as its normal form

### ISSUE THREAD

**Issue by ponddy-edu** [l10n-tw/cwtex-q-fonts#13]
"真" is displayed as the variant. should be displayed as its normal form.
"真" 字型顯示為異體字, 應使用正體字方式顯示.
Reference: http://dict.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?quote_code=QTAyNzY4

**Comment by chenpanliao** [comment]
cwtex的宋體字是參考康熙字典的寫法，也就是採用「眞」字寫法。雖然Unicode對「真」和「眞」可對應至不同字符，但採用「眞」寫法有其歷史與排版的理由，而正體字筆畫一直都不是此字體的主要的考量。如果您十分注重所謂的「官方正體字筆畫」，唯有採用教育部或其它公司推出的標準宋體字或標準明體字體，較有保障。

**Comment by ponddy-edu** [comment]
謝謝您的意見, 後來已改用企業版權的雅坊書法大師中楷體
