### ISSUE TITLE
如何取得 TTF 字體？

### ISSUE THREAD

**Issue by iblislin** [l10n-tw/cwtex-q-fonts#14]
https://github.com/l10n-tw/cwtex-q-fonts#%E4%B8%8B%E8%BC%89-ttf-%E5%AD%97%E9%AB%94

這個 section 提到有 TTF 字體可供下載，但是在 release page 的 tarball 中沒有 TTF 字體，請問如何產生 TTF 字體 或是 如何使用這些 sfd 檔案？

**Comment by zerng07** [comment]
https://github.com/l10n-tw/cwtex-q-fonts-TTFs/releases
或
https://github.com/l10n-tw/cwtex-q-fonts-TTFs/tree/master/ttf
