### ISSUE TITLE
Some glyphs are missing.

### ISSUE THREAD

**Issue by ghost** [l10n-tw/cwtex-q-fonts#16]
Hello, everyone!
Thank you for your excellent work!

However, I can't find some glyphs, which the font reports to be having. (Particularly related to the Simplified Chinese.)

Please have a look at the attached screenshot of the KDE Font Manager.
I have selected the following phrase as a test phrase:
你好，妳，国国，产產
And the simplified characters are not rendered, although is is displayed in the "Simplified Chinese" writing system selector.
![image](https://user-images.githubusercontent.com/2077025/58538551-f1963800-8227-11e9-920c-bffb67feb0b8.png)

**Comment by phineas-pta** [comment]
I don't think this font is for simplified Chinese, you should use other fonts

**Comment by chenpanliao** [comment]
I'm sorry for that this project would not cover simplified Chinese characters. Please seek some other fonts. Thank you.
