### ISSUE TITLE
Add space and nonbreakingspace

### ISSUE THREAD

**Issue by davelab6** [l10n-tw/cwtex-q-fonts#2]
In these fonts there is no space (0x0020) nor nonbreakingspace (0x00a0) glyphs, so the 'notdef' inked glyph is shown when they are used. This seems like a bug and I suggest adding them :)

**Comment by zerng07** [comment]
Thank you for reporting this! :)
We will work on it.

**Comment by zerng07** [comment]
The last commit f620dae should have fixed this! :)
You could have a test.

**Comment by davelab6** [comment]
Thanks! Not sure when I will get to test but have bookmarked this to do so soon :)
