### ISSUE TITLE
黑體中的韓文音節字元對應錯誤

### ISSUE THREAD

**Issue by hiunnhue** [l10n-tw/cwtex-q-fonts#3]
黑體 (cwTeW Q Hei) 裡面的韓文字元對應錯誤，例如 `U+AC04` 應該是 간 (gan) ，但顯示的卻是 갆 (ganh)

請見截圖：

![cwtexq_korean](https://cloud.githubusercontent.com/assets/1015601/14065095/4fe87212-f44e-11e5-9435-ca8f3710c333.png)

**Comment by zerng07** [comment]
收到。

很有可能當初從韓文字型複製字圖時就出錯了，有空會處理～

**Comment by zerng07** [comment]
瞭解問題了，字符都移動了兩個字符的位置，需要重新對應一下。

**Comment by zerng07** [comment]
commit 6115fd4 應該已經修正此問題；我重新匯入了最近一版 Un-Dotum 的韓文字母（cwtex 當初匯入的都是 Un 的韓文字，這次我取用的是2008年發行版本）。

ㄅㄆㄇㄈ也順便更新為黑體風格了。

幫忙測試看看吧～ 感恩！

**Comment by zerng07** [comment]
不過看起來好像細了一點，還是當初匯入的是 Un Dotum Bold？我晚點自己測試看看好了。

**Comment by zerng07** [comment]
commit fe3cb28 為取自 Un-Dotum Bold 粗的版本，煩請測試看看哪個比較適合，感謝～

**Comment by hiunnhue** [comment]
1. 抱歉我不知道要怎麼產生字型檔，所以就只是用 FontForge 打開來看。而且我也沒逐一檢查，只是隨機挑選幾個，但應該都沒問題。
2. 粗的版本好像太粗了，感覺原本的比較合適
3. 另外發現其他的對應錯誤：

![wrong_01](https://cloud.githubusercontent.com/assets/1015601/14405298/3f052b3c-febe-11e5-9cbb-8474f2c7de1b.png)

**Comment by zerng07** [comment]
FontForge 左上角「檔案」>「產生字型」，取消檢查的勾選可直接輸出字型。

FontForge 算繪的效果跟系統不一樣，裝起來比較能實際反映粗細。

瞭解，再改善！

**Comment by hiunnhue** [comment]
拍了截圖：

![bold](https://cloud.githubusercontent.com/assets/1015601/14407875/3ff74018-ff0c-11e5-97bb-e0fae6b77fb8.png)

當初的(對應錯誤的)版本好像是粗的沒錯，但總覺得粗版的韓文都比漢字還粗了…

**Comment by zerng07** [comment]
我這次 5588a38 把 Un Dotum 一般版加粗了 1.15 倍來逼近 cwTeX Q Hei 漢字部分的粗細，並且將你紅線圈起來的部分用 Un Dotum 的版本取代了。

英文字和特殊英文字的字重差別，來自於 cwTeX Q Hei 的英文字取自 LCG-en 字型，特殊英文字取自 Un Dotum Bold，所以… 嗯。透過 Un Dotum 一般版加粗 1.15 倍的做法應該有縮小兩者間的差距了，但還是不夠好。

因為 LCG-en 確實滿細的，或許可以重新考慮統一用同個 GPL 授權字型來替換，風格會比較一致…

還麻煩測試一下有沒有什麼大問題啊，沒問題就用這個修正囉。

**Comment by hiunnhue** [comment]
先貼截圖：

![bold_02](https://cloud.githubusercontent.com/assets/1015601/14410067/674d437e-ff57-11e5-9e83-93b93eca4d58.png)

## 
1. 對應錯誤的地方已經修正了 :+1: 
2. 韓文字看起來還是有一點點粗？`悠久한` 比較明顯，但也可能是韓文字尺寸稍微較大的緣故？
3. 英文字型還是看得出差別，但已經好很多
4. `U+55E7` 是 `嗧` (上加下侖)，不是`囗`
5. `U+FE4F` 是 `wavy low line`，但字型裡的字圖卻在上方
6. 上述兩個錯誤，在純漢字的 `cwTeX Q HeiZH Bold` 也有
7. 雖然名稱叫粗黑體，但實際上和思源黑體 Regular 差不多粗，但又無法在 LibO 裡面用粗體按鈕來加粗  :confused:

**Comment by zerng07** [comment]
1. OK
2. 韓文字筆畫少，要比漢字粗一點灰度才會比較一致。韓文字筆畫少，字面大，看起來字就比較大。如果最好當然是希望能和協一點，但畢竟是直接引入的比較難做 XD
3. 這個就看要不要整個西文都改掉了，可以另發 issue 討論
4. 啊，這個我細字版有發現砍掉，但粗字版又重新被我引入 regression 了，畢竟主題不同，另發 issue 追蹤嗧字的繪製好了
5. 好，也建議另開 issue 處理，或者放在同一篇 issue 列出就好
6. 我另外弄的 ZenJia Hei 就是希望拿來作 Regular 粗，然後用 Fontforge 的字重加粗程式另外生出 Bold 粗再來微調，不過這個要花點時間或機運。之前跑加粗時 Fontforge 都會掛掉失敗... Orz

**Comment by hiunnhue** [comment]
OK，我另外開 issue 給嗧和 wavy low line 了
